UserAuth/UserAuth/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path,re_path
from basicApp import views

urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^basicApp/',include('basicApp.urls')),
    re_path(r'^logout/$',views.user_logout,name='logout'),
]

UserAuth/basicApp/urls.py
from django.urls import path,re_path
from basicApp import views

app_name = 'basicApp'

urlpatterns=[
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^user_login/$',views.user_login,name='user_login'),
    re_path(r'^game/$',views.game,name='game'),
]

UserAuth/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

UserAuth/basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model= UserProfileInfo
        fields= ('portfolio_site','profile_pic')

UserAuth/basicApp/views.py
from django.shortcuts import render
from basicApp.forms import UserForm,UserProfileInfoForm
# Create your views here.


#import for LOGIN/LOGOUT
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required

#For game
def game(request):
    return render(request,'basicApp/FourConnect.html')

#For register
def index(request):
    return render(request,'basicApp/index.html')

#FOR logout
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered=False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,"basicApp/registration.html",
                               {'registered':registered,
                                'user_form':user_form,
                                'profile_form':profile_form})

#For LOGIN
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        userDict={'userName':username}
        password = request.POST.get('password')

        user =authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                # return render(request,'basicApp/base.html',context=userDict)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tried to login")
            print("Username:{} Password:{}".format(username,password))
            return HttpResponse('INVALID LOGIN DETAILS')
    else:
        # return HttpResponse("You're not registered")
        return render(request,'basicApp/login.html',{})

UserAuth/templates/basicApp/FourConnect.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Connected Four</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/fourconnected.css" %}">
    <script
      src="https://code.jquery.com/jquery-3.4.1.js"
      integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
      crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="Container">
      <nav>
          <img src="{% static "CNC4(1).png" %}" alt="Connect Four">
          <h1>Welcome to Connect Four</h1>
      </nav>
      <section class="sec1" align="center">
        <h2>The Objective of this game is to connect Four Dots</h2>
        <h3 id="pname">Let's Get Started</h3>
      </section>
        <section class="sec2" align="center">
            <div class="div1">
              <h3>Click on first row to fill dots</h3>
              <table class="plyrname">
                <tr>
                  <td><h4>Player One:</h4></td>
                  <td> <h4 id="p1"></h4> </td>
                </tr>
                <tr>
                  <td><h4 >Player Two:</h4></td>
                  <td> <h4 id="p2"></h4> </td>
                </tr>
                <tr>
                  <td><h4>Toss:</h4></td>
                  <td> <h4 id="Toss"></h4> </td>
                </tr>
                <tr>
                  <td> <h4>Play Turn:</h4></td>
                  <td> <h4 id="Turn"></h4> </td>
                </tr>
                <tr>
                  <td> <h4 id="res2">Results:</h4></td>
                  <td> <h4 id="res3"></h4> </td>
                </tr>
                <tr>
                  <td><p id="plyagn">Refresh the page to Play Again</p></td>
                </tr>
              </table>
            </div>
          <table align="center" class="board">
              <tr id="tr1">
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
              </tr>
              <tr id="tr2">
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
              </tr>
              <tr id="tr3">
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
              </tr>
              <tr id="tr4">
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
              </tr>
              <tr id="tr5">
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
              </tr>
              <tr id="tr6">
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
                <td><button type="button">c</button> </td>
              </tr>
          </table>
      </section>
        <!-- <input type="submit" align="center" name="Restart" value="PlayAgain"> -->
      </div>
    <script src="{% static "javascript/fourconnected.js" %}" charset="utf-8"></script>
  </body>
</html>

UserAuth/templates/basicApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static navbar-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="nav-item"><a class="navbar-brand" href="{% url "index" %}">basicApp</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "admin:index" %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "basicApp:register" %}">Register</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "basicApp:game" %}">Game</a></li>
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'basicApp:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

UserAuth/templates/basicApp/index.html
{% extends "basicApp/base.html" %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Django level 5</h1>
    </div>
  {% endblock %}

UserAuth/templates/basicApp/login.html
{% extends 'basicApp/base.html' %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basicApp:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter User Name">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="Submit" value="Login">
    </form>
</div>

{% endblock %}

UserAuth/templates/basicApp/registration.html
{% extends "basicApp/base.html" %}
{% load static %}
  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thankyou for Registering</h1>
      {% else %}
        <h1>Register here !</h1>
        <h3>Fill out the form:</h3>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p}}
          {{ profile_form.as_p}}
          <input type="submit" value="Register">
        </form>
      {% endif %}
    </div>
  {% endblock %}